# Generated by Django 5.2.16 on 2026-08-03 16:40

import contas.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contas', '0001_instituicao_usuario'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', contas.models.UsuarioManager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='usuario',
            name='contas_email_por_instituicao',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='criado_em',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(blank=True, choices=[('ALUNO', 'Aluno'), ('PROFESSOR', 'Professor'), ('DIRETOR', 'Diretor')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(fields=('instituicao', 'email'), name='contas_email_unico_instituicao'),
        ),
    ]
