# Generated by Django 5.2.16 on 2026-08-03 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDeAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=120)),
                ('objeto_tipo', models.CharField(max_length=120)),
                ('objeto_id', models.CharField(max_length=80)),
                ('motivo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
