# Generated by Django 5.2.16 on 2026-08-03 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_registrodeauditoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConviteProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expira_em', models.DateTimeField()),
                ('aceito_em', models.DateTimeField(blank=True, null=True)),
                ('envio_email_status', models.CharField(default='PENDENTE', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('convidado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convites_enviados', to=settings.AUTH_USER_MODEL)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convites_professor', to='contas.instituicao')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('aceito_em__isnull', True)), fields=('instituicao', 'email'), name='contas_convite_pendente_unico')],
            },
        ),
    ]
