# Generated by Django 5.2.16 on 2026-08-05 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0007_mantenedora_vitis_souls'),
        ('ia', '0002_chamadaia_classe_tarefa_chamadaia_concluida_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('PRISMA', 'Prisma'), ('PRISMA_PRO', 'Prisma Pro'), ('PRISMA_ULTRA', 'Prisma Ultra')], max_length=16, unique=True)),
                ('nome', models.CharField(max_length=80)),
                ('preco_por_conta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limite_percentual_por_conta', models.DecimalField(decimal_places=4, max_digits=8)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['preco_por_conta', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CotaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cota_ia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssinaturaInstituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('instituicao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura_prisma', to='contas.instituicao')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas', to='limites.planoinstitucional')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.CharField(max_length=80)),
                ('modelo', models.CharField(max_length=160)),
                ('classe_tarefa', models.CharField(max_length=20)),
                ('percentual', models.DecimalField(decimal_places=4, max_digits=7)),
                ('custo_bruto', models.DecimalField(decimal_places=8, default=0, max_digits=14)),
                ('metadados', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos_ia', to='contas.instituicao')),
                ('referencia', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='consumo_percentual', to='ia.chamadaia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['instituicao', 'usuario', 'criado_em'], name='limites_con_institu_2d66be_idx'), models.Index(fields=['fornecedor', 'modelo', 'criado_em'], name='limites_con_fornece_58635e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('percentual__gt', 0)), name='limites_consumo_percentual_valido')],
            },
        ),
    ]
