"""A assinatura da instituicao passa a declarar cobranca mensal ou anual."""
# Generated by Django 5.2.16 on 2026-08-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limites', '0003_consumo_ciclo'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinaturainstituicao',
            name='periodicidade',
            field=models.CharField(choices=[('MENSAL', 'Mensal'), ('ANUAL', 'Anual')], default='MENSAL', max_length=6),
        ),
    ]
