# Generated by Django 5.2.16 on 2026-08-03 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0002_turma_professor_responsavel_configuracaonota_and_more'),
        ('arquivos', '0001_initial'),
        ('contas', '0005_registrodeauditoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('origem', models.CharField(choices=[('MANUAL', 'Manual'), ('IA', 'Inteligencia artificial')], max_length=10)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('OFICIAL', 'Oficial'), ('ARQUIVADO', 'Arquivado')], default='RASCUNHO', max_length=10)),
                ('revisado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('arquivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materiais', to='arquivos.arquivo')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiais_criados', to=settings.AUTH_USER_MODEL)),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materiais', to='academico.disciplina')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiais', to='contas.instituicao')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materiais_revisados', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materiais', to='academico.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('origem', models.CharField(choices=[('MANUAL', 'Manual'), ('IA', 'Inteligencia artificial')], max_length=10)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('OFICIAL', 'Oficial'), ('ARQUIVADO', 'Arquivado')], default='RASCUNHO', max_length=10)),
                ('revisado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provas_criadas', to=settings.AUTH_USER_MODEL)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provas', to='academico.disciplina')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provas', to='contas.instituicao')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provas_revisadas', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provas', to='academico.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('enunciado', models.TextField()),
                ('alternativas', models.JSONField(blank=True, default=list)),
                ('gabarito', models.TextField()),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questoes', to='conteudo.prova')),
            ],
            options={
                'ordering': ['ordem', 'id'],
                'constraints': [models.UniqueConstraint(fields=('prova', 'ordem'), name='conteudo_ordem_questao_unica')],
            },
        ),
    ]
