# Generated by Django 5.2.16 on 2026-08-05 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0001_initial'),
        ('ia', '0003_remove_chamadaia_creditos_debitados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='chamada_ia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materiais_gerados', to='ia.chamadaia'),
        ),
        migrations.AddField(
            model_name='material',
            name='formato',
            field=models.CharField(choices=[('MATERIAL', 'Material'), ('RESUMO', 'Resumo'), ('FLASHCARDS', 'Flashcards'), ('AUDIO', 'Audio-revisao'), ('IMPORTADO', 'Importado')], default='MATERIAL', max_length=12),
        ),
    ]
