# Generated by Django 5.2.16 on 2026-08-05 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0007_mantenedora_vitis_souls'),
        ('conteudo', '0002_material_chamada_ia_material_formato'),
        ('ia', '0003_remove_chamadaia_creditos_debitados_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=120)),
                ('estilo', models.CharField(default='ENEM', max_length=40)),
                ('quantidade', models.PositiveSmallIntegerField()),
                ('foco_dificuldades', models.BooleanField(default=True)),
                ('correcao_comentada', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluido')], default='EM_ANDAMENTO', max_length=12)),
                ('resultado_percentual', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='simulados_alunos', to=settings.AUTH_USER_MODEL)),
                ('chamada_ia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='simulados_gerados', to='ia.chamadaia')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='simulados_alunos', to='contas.instituicao')),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QuestaoSimulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField()),
                ('enunciado', models.TextField()),
                ('alternativas', models.JSONField(default=list)),
                ('gabarito', models.CharField(max_length=2)),
                ('resposta', models.CharField(blank=True, max_length=2)),
                ('simulado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='conteudo.simulado')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='simulado',
            index=models.Index(fields=['aluno', 'status', 'criado_em'], name='conteudo_si_aluno_i_8d29fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='questaosimulado',
            constraint=models.UniqueConstraint(fields=('simulado', 'ordem'), name='conteudo_ordem_questao_simulado_unica'),
        ),
    ]
