"""Material e prova ganham prazo de entrega da atividade proposta."""
# Generated by Django 5.2.16 on 2026-08-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0003_simulado_questaosimulado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='prazo_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prova',
            name='prazo_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
