# Generated by Django 5.2.16 on 2026-08-06 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0004_turma_professores'),
        ('contas', '0008_provider_e_instituicao_prisma'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('prazo_entrega', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avisos_enviados', to=settings.AUTH_USER_MODEL)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avisos', to='contas.instituicao')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avisos', to='academico.turma')),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['turma', 'criado_em'], name='avisos_avis_turma_i_ebdbcf_idx')],
            },
        ),
    ]
