# Generated by Django 5.2.16 on 2026-08-03 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('contas', '0005_registrodeauditoria'),
        ('ia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoAlertaSaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limiar', models.DecimalField(decimal_places=4, max_digits=14)),
                ('instituicao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_alerta_creditos', to='contas.instituicao')),
            ],
        ),
        migrations.CreateModel(
            name='TravaSaldoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trava_saldo_creditos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CREDITO', 'Credito'), ('DEBITO', 'Debito'), ('ALOCACAO', 'Alocacao'), ('ESTORNO', 'Estorno')], max_length=10)),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=14)),
                ('motivo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_criados', to=settings.AUTH_USER_MODEL)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='contas.instituicao')),
                ('referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='ia.chamadaia')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='academico.turma')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['instituicao', 'usuario'], name='creditos_la_institu_498c6d_idx'), models.Index(fields=['instituicao', 'turma'], name='creditos_la_institu_819fd1_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='creditos_quantidade_positiva'), models.UniqueConstraint(condition=models.Q(('tipo', 'DEBITO')), fields=('referencia', 'tipo'), name='creditos_debito_unico_por_referencia')],
            },
        ),
    ]
