# Generated by Django 5.2.16 on 2026-08-05 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0007_mantenedora_vitis_souls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('disciplina', models.CharField(blank=True, max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('agendado_para', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDA', 'Concluida'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_estudos', to=settings.AUTH_USER_MODEL)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendas_estudo', to='contas.instituicao')),
            ],
            options={
                'ordering': ['agendado_para', 'id'],
                'indexes': [models.Index(fields=['aluno', 'status', 'agendado_para'], name='aluno_agend_aluno_i_86f95e_idx')],
            },
        ),
    ]
