# Generated by Django 5.2.16 on 2026-08-06 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoProvedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.CharField(max_length=80, unique=True)),
                ('modalidade', models.CharField(choices=[('POR_TOKEN', 'Cobrado por token'), ('ASSINATURA', 'Assinatura mensal')], max_length=12)),
                ('mensalidade', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('contas_atendidas', models.PositiveIntegerField(default=1)),
                ('chamadas_por_conta_no_mes', models.PositiveIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['fornecedor'],
            },
        ),
        migrations.CreateModel(
            name='TarifaModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=160, unique=True)),
                ('preco_por_mil_entrada', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('preco_por_mil_saida', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('ativo', models.BooleanField(default=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='custos.contratoprovedor')),
            ],
            options={
                'ordering': ['modelo'],
            },
        ),
    ]
