# Generated by Django 5.2.16 on 2026-08-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custos', '0002_catalogo_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoprovedor',
            name='fator_sobre_referencia',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='tarifamodelo',
            name='referencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contratoprovedor',
            name='modalidade',
            field=models.CharField(choices=[('POR_TOKEN', 'Cobrado por token'), ('ASSINATURA_RATEIO', 'Assinatura — rateio da mensalidade'), ('ASSINATURA_RELATIVA', 'Assinatura — fator sobre a referência')], max_length=20),
        ),
    ]
