# Generated by Django 5.2.16 on 2026-08-03 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0005_registrodeauditoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Turma', max_length=120)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='contas.instituicao')),
            ],
        ),
    ]
