# Generated by Django 5.2.16 on 2026-08-03 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
        ('contas', '0005_registrodeauditoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='professor_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turmas_responsavel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ConfiguracaoNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_minima', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('nota_maxima', models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ('instituicao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_nota', to='contas.instituicao')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disciplinas', to='contas.instituicao')),
            ],
        ),
        migrations.AddField(
            model_name='turma',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='academico.disciplina'),
        ),
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('justificada', models.BooleanField(default=False)),
                ('motivo', models.CharField(blank=True, max_length=240)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faltas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faltas_criadas', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faltas', to='academico.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrou_em', models.DateField(auto_now_add=True)),
                ('saiu_em', models.DateField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='academico.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.CharField(max_length=120)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('origem', models.CharField(choices=[('MANUAL', 'Manual'), ('IA', 'Inteligencia artificial')], default='MANUAL', max_length=10)),
                ('oficial', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_em', models.DateTimeField(auto_now=True)),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_alteradas', to=settings.AUTH_USER_MODEL)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_criadas', to=settings.AUTH_USER_MODEL)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='academico.disciplina')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='academico.turma')),
            ],
        ),
        migrations.AddConstraint(
            model_name='disciplina',
            constraint=models.UniqueConstraint(fields=('instituicao', 'nome'), name='academico_disciplina_unica_instituicao'),
        ),
        migrations.AddConstraint(
            model_name='falta',
            constraint=models.UniqueConstraint(fields=('turma', 'aluno', 'data'), name='academico_falta_unica_dia'),
        ),
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(condition=models.Q(('saiu_em__isnull', True)), fields=('turma', 'aluno'), name='academico_matricula_ativa_unica'),
        ),
        migrations.AddConstraint(
            model_name='nota',
            constraint=models.UniqueConstraint(fields=('turma', 'disciplina', 'aluno', 'avaliacao'), name='academico_nota_unica_avaliacao'),
        ),
        migrations.AddConstraint(
            model_name='nota',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gte', 0), ('valor__lte', 10)), name='academico_nota_entre_zero_e_dez'),
        ),
    ]
