# Generated by Django 5.2.16 on 2026-08-03 18:43

import arquivos.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0005_registrodeauditoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome_original', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to=arquivos.models.caminho_arquivo)),
                ('tipo_mime', models.CharField(max_length=120)),
                ('tamanho_bytes', models.PositiveBigIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arquivos_enviados', to=settings.AUTH_USER_MODEL)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arquivos', to='contas.instituicao')),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['instituicao', 'criado_em'], name='arquivos_ar_institu_ce1bd5_idx')],
            },
        ),
    ]
