# Generated by Django 5.2.16 on 2026-08-03 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_registrodeauditoria'),
        ('ia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chamadaia',
            name='classe_tarefa',
            field=models.CharField(choices=[('TUTORIA', 'Tutoria'), ('GERACAO', 'Geracao'), ('CORRECAO', 'Correcao'), ('RESUMO', 'Resumo')], default='TUTORIA', max_length=10),
        ),
        migrations.AddField(
            model_name='chamadaia',
            name='concluida_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamadaia',
            name='creditos_debitados',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='chamadaia',
            name='custo_bruto',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='chamadaia',
            name='erro_codigo',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='chamadaia',
            name='instituicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chamadas_ia', to='contas.instituicao'),
        ),
        migrations.AddField(
            model_name='chamadaia',
            name='modelo',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='chamadaia',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('SUCESSO', 'Sucesso'), ('ERRO', 'Erro')], default='PENDENTE', max_length=10),
        ),
        migrations.AddField(
            model_name='chamadaia',
            name='tokens_entrada',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chamadaia',
            name='tokens_saida',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chamadaia',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chamadas_ia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chamadaia',
            index=models.Index(fields=['instituicao', 'usuario', 'status'], name='ia_chamadai_institu_2fa6b4_idx'),
        ),
    ]
