# Generated by Django 5.2.16 on 2026-08-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0002_chamadaia_classe_tarefa_chamadaia_concluida_em_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamadaia',
            name='creditos_debitados',
        ),
        migrations.AddField(
            model_name='chamadaia',
            name='fornecedor',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='chamadaia',
            name='percentual_debitado',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
    ]
