# Generated by Django 5.2.16 on 2026-08-03 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ia', '0002_chamadaia_classe_tarefa_chamadaia_concluida_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('retencao_expira_em', models.DateTimeField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversas_tutor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['criada_em', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MemoriaConsolidada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(blank=True, max_length=120)),
                ('topico', models.CharField(blank=True, max_length=160)),
                ('resumo', models.TextField()),
                ('periodo_inicio', models.DateTimeField(blank=True, null=True)),
                ('periodo_fim', models.DateTimeField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memorias_tutor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criada_em', '-id'],
                'indexes': [models.Index(fields=['aluno', 'disciplina', 'topico', '-criada_em'], name='memoria_mem_aluno_i_657b20_idx')],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('ALUNO', 'Aluno'), ('TUTOR', 'Tutor')], max_length=5)),
                ('conteudo', models.TextField()),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('chamada_ia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_tutor', to='ia.chamadaia')),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='memoria.conversa')),
            ],
            options={
                'ordering': ['criada_em', 'id'],
                'indexes': [models.Index(fields=['conversa', 'criada_em'], name='memoria_men_convers_e82144_idx')],
            },
        ),
    ]
