# Generated by Django 5.2.16 on 2026-08-05 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0002_conversa_disciplina_conversa_topico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estilo', models.CharField(choices=[('SOCRATICO', 'Socratico'), ('DIRETO', 'Direto')], default='SOCRATICO', max_length=10)),
                ('dificuldade', models.CharField(choices=[('BASICO', 'Basico'), ('MEDIO', 'Medio'), ('DIFICIL', 'Dificil')], default='MEDIO', max_length=10)),
                ('foco_exame', models.CharField(default='ENEM', max_length=40)),
                ('tamanho_resposta', models.CharField(choices=[('CURTA', 'Curta'), ('DETALHADA', 'Detalhada')], default='CURTA', max_length=12)),
                ('correcao_comentada', models.BooleanField(default=True)),
                ('foco_dificuldades', models.BooleanField(default=True)),
                ('resposta_audio', models.BooleanField(default=False)),
                ('usar_arquivos_contexto', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_tutor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
